name = "xabar"
main = "src/index.js"
compatibility_date = "2026-07-10"

[assets]
directory = "../dist"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "alomat_signals"
database_id = "247e9fe2-2744-4662-83f0-18e58719d8d3"
migrations_dir = "migrations"
